/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BadRequest,
  Journey,
  JourneyRequestDto,
} from '../models/index';
import {
    BadRequestFromJSON,
    BadRequestToJSON,
    JourneyFromJSON,
    JourneyToJSON,
    JourneyRequestDtoFromJSON,
    JourneyRequestDtoToJSON,
} from '../models/index';

export interface JourneyControllerQueryJourneyRequest {
    journeyRequestDto: JourneyRequestDto;
}

/**
 * 
 */
export class JourneyApi extends runtime.BaseAPI {

    /**
     * queries a journey
     */
    async journeyControllerQueryJourneyRaw(requestParameters: JourneyControllerQueryJourneyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Journey>>> {
        if (requestParameters.journeyRequestDto === null || requestParameters.journeyRequestDto === undefined) {
            throw new runtime.RequiredError('journeyRequestDto','Required parameter requestParameters.journeyRequestDto was null or undefined when calling journeyControllerQueryJourney.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/journey`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JourneyRequestDtoToJSON(requestParameters.journeyRequestDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(JourneyFromJSON));
    }

    /**
     * queries a journey
     */
    async journeyControllerQueryJourney(journeyRequestDto: JourneyRequestDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Journey>> {
        const response = await this.journeyControllerQueryJourneyRaw({ journeyRequestDto: journeyRequestDto }, initOverrides);
        return await response.value();
    }

}
