/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Stats,
} from '../models/index';
import {
    StatsFromJSON,
    StatsToJSON,
} from '../models/index';

/**
 * 
 */
export class StatsApi extends runtime.BaseAPI {

    /**
     */
    async statsControllerGetStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Stats>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/stats`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatsFromJSON(jsonValue));
    }

    /**
     */
    async statsControllerGetStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Stats> {
        const response = await this.statsControllerGetStatsRaw(initOverrides);
        return await response.value();
    }

}
