/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DelayWithRoute
 */
export interface DelayWithRoute {
    /**
     * 
     * @type {object}
     * @memberof DelayWithRoute
     */
    route: object;
}

/**
 * Check if a given object implements the DelayWithRoute interface.
 */
export function instanceOfDelayWithRoute(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "route" in value;

    return isInstance;
}

export function DelayWithRouteFromJSON(json: any): DelayWithRoute {
    return DelayWithRouteFromJSONTyped(json, false);
}

export function DelayWithRouteFromJSONTyped(json: any, ignoreDiscriminator: boolean): DelayWithRoute {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'route': json['route'],
    };
}

export function DelayWithRouteToJSON(value?: DelayWithRoute | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'route': value.route,
    };
}

