/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Footpath
 */
export interface Footpath {
    /**
     * Total duration of the footpath in seconds.
     * @type {number}
     * @memberof Footpath
     */
    totalDuration: number;
    /**
     * Total distance of the footpath in meters.
     * @type {number}
     * @memberof Footpath
     */
    totalDistance: number;
}

/**
 * Check if a given object implements the Footpath interface.
 */
export function instanceOfFootpath(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "totalDuration" in value;
    isInstance = isInstance && "totalDistance" in value;

    return isInstance;
}

export function FootpathFromJSON(json: any): Footpath {
    return FootpathFromJSONTyped(json, false);
}

export function FootpathFromJSONTyped(json: any, ignoreDiscriminator: boolean): Footpath {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalDuration': json['totalDuration'],
        'totalDistance': json['totalDistance'],
    };
}

export function FootpathToJSON(value?: Footpath | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalDuration': value.totalDuration,
        'totalDistance': value.totalDistance,
    };
}

