/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InterchangeReachableStat
 */
export interface InterchangeReachableStat {
    /**
     * Status of the leg stats.
     * @type {string}
     * @memberof InterchangeReachableStat
     */
    status: InterchangeReachableStatStatusEnum;
    /**
     * Probability of interchange(s) (following current leg) that were successful in the past.
     * @type {number}
     * @memberof InterchangeReachableStat
     */
    interchangeReachableProbability: number;
}


/**
 * @export
 */
export const InterchangeReachableStatStatusEnum = {
    Available: 'available',
    Unavailable: 'unavailable'
} as const;
export type InterchangeReachableStatStatusEnum = typeof InterchangeReachableStatStatusEnum[keyof typeof InterchangeReachableStatStatusEnum];


/**
 * Check if a given object implements the InterchangeReachableStat interface.
 */
export function instanceOfInterchangeReachableStat(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "interchangeReachableProbability" in value;

    return isInstance;
}

export function InterchangeReachableStatFromJSON(json: any): InterchangeReachableStat {
    return InterchangeReachableStatFromJSONTyped(json, false);
}

export function InterchangeReachableStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): InterchangeReachableStat {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'interchangeReachableProbability': json['interchangeReachableProbability'],
    };
}

export function InterchangeReachableStatToJSON(value?: InterchangeReachableStat | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'interchangeReachableProbability': value.interchangeReachableProbability,
    };
}

