/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    DelayStats,
    instanceOfDelayStats,
    DelayStatsFromJSON,
    DelayStatsFromJSONTyped,
    DelayStatsToJSON,
} from './DelayStats';
import {
    UnavailableStats,
    instanceOfUnavailableStats,
    UnavailableStatsFromJSON,
    UnavailableStatsFromJSONTyped,
    UnavailableStatsToJSON,
} from './UnavailableStats';

/**
 * @type JourneyStatsAggregatedDelayStats
 * Aggregated delay statistics of all journey's legs.
 * @export
 */
export type JourneyStatsAggregatedDelayStats = { status: 'available' } & DelayStats | { status: 'unavailable' } & UnavailableStats;

export function JourneyStatsAggregatedDelayStatsFromJSON(json: any): JourneyStatsAggregatedDelayStats {
    return JourneyStatsAggregatedDelayStatsFromJSONTyped(json, false);
}

export function JourneyStatsAggregatedDelayStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): JourneyStatsAggregatedDelayStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['status']) {
        case 'available':
            return {...DelayStatsFromJSONTyped(json, true), status: 'available'};
        case 'unavailable':
            return {...UnavailableStatsFromJSONTyped(json, true), status: 'unavailable'};
        default:
            throw new Error(`No variant of JourneyStatsAggregatedDelayStats exists with 'status=${json['status']}'`);
    }
}

export function JourneyStatsAggregatedDelayStatsToJSON(value?: JourneyStatsAggregatedDelayStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['status']) {
        case 'available':
            return DelayStatsToJSON(value);
        case 'unavailable':
            return UnavailableStatsToJSON(value);
        default:
            throw new Error(`No variant of JourneyStatsAggregatedDelayStats exists with 'status=${value['status']}'`);
    }

}

