/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    InterchangeReachableStat,
    instanceOfInterchangeReachableStat,
    InterchangeReachableStatFromJSON,
    InterchangeReachableStatFromJSONTyped,
    InterchangeReachableStatToJSON,
} from './InterchangeReachableStat';
import {
    UnavailableStats,
    instanceOfUnavailableStats,
    UnavailableStatsFromJSON,
    UnavailableStatsFromJSONTyped,
    UnavailableStatsToJSON,
} from './UnavailableStats';

/**
 * @type JourneyStatsAggregatedInterchangeReachableStat
 * Aggregated probability of reaching interchanges on journey.
 * @export
 */
export type JourneyStatsAggregatedInterchangeReachableStat = { status: 'available' } & InterchangeReachableStat | { status: 'unavailable' } & UnavailableStats;

export function JourneyStatsAggregatedInterchangeReachableStatFromJSON(json: any): JourneyStatsAggregatedInterchangeReachableStat {
    return JourneyStatsAggregatedInterchangeReachableStatFromJSONTyped(json, false);
}

export function JourneyStatsAggregatedInterchangeReachableStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): JourneyStatsAggregatedInterchangeReachableStat {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['status']) {
        case 'available':
            return {...InterchangeReachableStatFromJSONTyped(json, true), status: 'available'};
        case 'unavailable':
            return {...UnavailableStatsFromJSONTyped(json, true), status: 'unavailable'};
        default:
            throw new Error(`No variant of JourneyStatsAggregatedInterchangeReachableStat exists with 'status=${json['status']}'`);
    }
}

export function JourneyStatsAggregatedInterchangeReachableStatToJSON(value?: JourneyStatsAggregatedInterchangeReachableStat | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['status']) {
        case 'available':
            return InterchangeReachableStatToJSON(value);
        case 'unavailable':
            return UnavailableStatsToJSON(value);
        default:
            throw new Error(`No variant of JourneyStatsAggregatedInterchangeReachableStat exists with 'status=${value['status']}'`);
    }

}

