/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { JourneyStatsAggregatedCancellationStat } from './JourneyStatsAggregatedCancellationStat';
import {
    JourneyStatsAggregatedCancellationStatFromJSON,
    JourneyStatsAggregatedCancellationStatFromJSONTyped,
    JourneyStatsAggregatedCancellationStatToJSON,
} from './JourneyStatsAggregatedCancellationStat';
import type { JourneyStatsAggregatedDelayStats } from './JourneyStatsAggregatedDelayStats';
import {
    JourneyStatsAggregatedDelayStatsFromJSON,
    JourneyStatsAggregatedDelayStatsFromJSONTyped,
    JourneyStatsAggregatedDelayStatsToJSON,
} from './JourneyStatsAggregatedDelayStats';
import type { JourneyStatsAggregatedInterchangeReachableStat } from './JourneyStatsAggregatedInterchangeReachableStat';
import {
    JourneyStatsAggregatedInterchangeReachableStatFromJSON,
    JourneyStatsAggregatedInterchangeReachableStatFromJSONTyped,
    JourneyStatsAggregatedInterchangeReachableStatToJSON,
} from './JourneyStatsAggregatedInterchangeReachableStat';

/**
 * 
 * @export
 * @interface JourneyStats
 */
export interface JourneyStats {
    /**
     * 
     * @type {JourneyStatsAggregatedDelayStats}
     * @memberof JourneyStats
     */
    aggregatedDelayStats: JourneyStatsAggregatedDelayStats;
    /**
     * 
     * @type {JourneyStatsAggregatedInterchangeReachableStat}
     * @memberof JourneyStats
     */
    aggregatedInterchangeReachableStat: JourneyStatsAggregatedInterchangeReachableStat;
    /**
     * 
     * @type {JourneyStatsAggregatedCancellationStat}
     * @memberof JourneyStats
     */
    aggregatedCancellationStat: JourneyStatsAggregatedCancellationStat;
}

/**
 * Check if a given object implements the JourneyStats interface.
 */
export function instanceOfJourneyStats(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "aggregatedDelayStats" in value;
    isInstance = isInstance && "aggregatedInterchangeReachableStat" in value;
    isInstance = isInstance && "aggregatedCancellationStat" in value;

    return isInstance;
}

export function JourneyStatsFromJSON(json: any): JourneyStats {
    return JourneyStatsFromJSONTyped(json, false);
}

export function JourneyStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): JourneyStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aggregatedDelayStats': JourneyStatsAggregatedDelayStatsFromJSON(json['aggregatedDelayStats']),
        'aggregatedInterchangeReachableStat': JourneyStatsAggregatedInterchangeReachableStatFromJSON(json['aggregatedInterchangeReachableStat']),
        'aggregatedCancellationStat': JourneyStatsAggregatedCancellationStatFromJSON(json['aggregatedCancellationStat']),
    };
}

export function JourneyStatsToJSON(value?: JourneyStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'aggregatedDelayStats': JourneyStatsAggregatedDelayStatsToJSON(value.aggregatedDelayStats),
        'aggregatedInterchangeReachableStat': JourneyStatsAggregatedInterchangeReachableStatToJSON(value.aggregatedInterchangeReachableStat),
        'aggregatedCancellationStat': JourneyStatsAggregatedCancellationStatToJSON(value.aggregatedCancellationStat),
    };
}

