/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    FootpathLeg,
    instanceOfFootpathLeg,
    FootpathLegFromJSON,
    FootpathLegFromJSONTyped,
    FootpathLegToJSON,
} from './FootpathLeg';
import {
    TransportationLeg,
    instanceOfTransportationLeg,
    TransportationLegFromJSON,
    TransportationLegFromJSONTyped,
    TransportationLegToJSON,
} from './TransportationLeg';

/**
 * @type JourneyLegsInner
 * 
 * @export
 */
export type JourneyLegsInner = { type: 'footpath' } & FootpathLeg | { type: 'transportation' } & TransportationLeg;

export function JourneyLegsInnerFromJSON(json: any): JourneyLegsInner {
    return JourneyLegsInnerFromJSONTyped(json, false);
}

export function JourneyLegsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): JourneyLegsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'footpath':
            return {...FootpathLegFromJSONTyped(json, true), type: 'footpath'};
        case 'transportation':
            return {...TransportationLegFromJSONTyped(json, true), type: 'transportation'};
        default:
            throw new Error(`No variant of JourneyLegsInner exists with 'type=${json['type']}'`);
    }
}

export function JourneyLegsInnerToJSON(value?: JourneyLegsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['type']) {
        case 'footpath':
            return FootpathLegToJSON(value);
        case 'transportation':
            return TransportationLegToJSON(value);
        default:
            throw new Error(`No variant of JourneyLegsInner exists with 'type=${value['type']}'`);
    }

}

