/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Leg } from './Leg';
import {
    LegFromJSON,
    LegFromJSONTyped,
    LegToJSON,
} from './Leg';

/**
 * 
 * @export
 * @interface Journey
 */
export interface Journey {
    /**
     * Legs of a journey.
     * @type {Array<Leg>}
     * @memberof Journey
     */
    legs?: Array<Leg>;
}

/**
 * Check if a given object implements the Journey interface.
 */
export function instanceOfJourney(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function JourneyFromJSON(json: any): Journey {
    return JourneyFromJSONTyped(json, false);
}

export function JourneyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Journey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'legs': !exists(json, 'legs') ? undefined : ((json['legs'] as Array<any>).map(LegFromJSON)),
    };
}

export function JourneyToJSON(value?: Journey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'legs': value.legs === undefined ? undefined : ((value.legs as Array<any>).map(LegToJSON)),
    };
}

