/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LocationDetails } from './LocationDetails';
import {
    LocationDetailsFromJSON,
    LocationDetailsFromJSONTyped,
    LocationDetailsToJSON,
} from './LocationDetails';
import type { Time } from './Time';
import {
    TimeFromJSON,
    TimeFromJSONTyped,
    TimeToJSON,
} from './Time';

/**
 * 
 * @export
 * @interface JourneyLocation
 */
export interface JourneyLocation {
    /**
     * Id of the location.
     * @type {string}
     * @memberof JourneyLocation
     */
    id?: string;
    /**
     * (Full) Name of the location.
     * @type {string}
     * @memberof JourneyLocation
     */
    name?: string;
    /**
     * Type of the location.
     * @type {string}
     * @memberof JourneyLocation
     */
    type?: JourneyLocationTypeEnum;
    /**
     * 
     * @type {LocationDetails}
     * @memberof JourneyLocation
     */
    details?: LocationDetails;
    /**
     * 
     * @type {Time}
     * @memberof JourneyLocation
     */
    arrival: Time;
    /**
     * 
     * @type {Time}
     * @memberof JourneyLocation
     */
    departure: Time;
}


/**
 * @export
 */
export const JourneyLocationTypeEnum = {
    Address: 'address',
    Crossing: 'crossing',
    Gis: 'gis',
    Locality: 'locality',
    Parking: 'parking',
    Platform: 'platform',
    Poi: 'poi',
    PoiHierarchy: 'poiHierarchy',
    Sharing: 'sharing',
    Stop: 'stop',
    Street: 'street',
    Suburb: 'suburb',
    Unknown: 'unknown',
    Singlehouse: 'singlehouse'
} as const;
export type JourneyLocationTypeEnum = typeof JourneyLocationTypeEnum[keyof typeof JourneyLocationTypeEnum];


/**
 * Check if a given object implements the JourneyLocation interface.
 */
export function instanceOfJourneyLocation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "arrival" in value;
    isInstance = isInstance && "departure" in value;

    return isInstance;
}

export function JourneyLocationFromJSON(json: any): JourneyLocation {
    return JourneyLocationFromJSONTyped(json, false);
}

export function JourneyLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): JourneyLocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'details': !exists(json, 'details') ? undefined : LocationDetailsFromJSON(json['details']),
        'arrival': TimeFromJSON(json['arrival']),
        'departure': TimeFromJSON(json['departure']),
    };
}

export function JourneyLocationToJSON(value?: JourneyLocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'type': value.type,
        'details': LocationDetailsToJSON(value.details),
        'arrival': TimeToJSON(value.arrival),
        'departure': TimeToJSON(value.departure),
    };
}

