/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Footpath } from './Footpath';
import {
    FootpathFromJSON,
    FootpathFromJSONTyped,
    FootpathToJSON,
} from './Footpath';

/**
 * 
 * @export
 * @interface LegInterchange
 */
export interface LegInterchange {
    /**
     * 
     * @type {Footpath}
     * @memberof LegInterchange
     */
    footpath: Footpath;
}

/**
 * Check if a given object implements the LegInterchange interface.
 */
export function instanceOfLegInterchange(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "footpath" in value;

    return isInstance;
}

export function LegInterchangeFromJSON(json: any): LegInterchange {
    return LegInterchangeFromJSONTyped(json, false);
}

export function LegInterchangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegInterchange {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'footpath': FootpathFromJSON(json['footpath']),
    };
}

export function LegInterchangeToJSON(value?: LegInterchange | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'footpath': FootpathToJSON(value.footpath),
    };
}

