/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LegInfoValidity
 */
export interface LegInfoValidity {
    /**
     * From which date on leg information becomes valid.
     * @type {Date}
     * @memberof LegInfoValidity
     */
    from: Date;
    /**
     * From which date on leg information is not valid any more. Sometimes a date far away in the future is used to state that there is no end date known yet.
     * @type {Date}
     * @memberof LegInfoValidity
     */
    to: Date;
}

/**
 * Check if a given object implements the LegInfoValidity interface.
 */
export function instanceOfLegInfoValidity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "from" in value;
    isInstance = isInstance && "to" in value;

    return isInstance;
}

export function LegInfoValidityFromJSON(json: any): LegInfoValidity {
    return LegInfoValidityFromJSONTyped(json, false);
}

export function LegInfoValidityFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegInfoValidity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'from': (new Date(json['from'])),
        'to': (new Date(json['to'])),
    };
}

export function LegInfoValidityToJSON(value?: LegInfoValidity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from': (value.from.toISOString()),
        'to': (value.to.toISOString()),
    };
}

