/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LocationDetails } from './LocationDetails';
import {
    LocationDetailsFromJSON,
    LocationDetailsFromJSONTyped,
    LocationDetailsToJSON,
} from './LocationDetails';

/**
 * 
 * @export
 * @interface LegOriginLocation
 */
export interface LegOriginLocation {
    /**
     * Id of the location.
     * @type {string}
     * @memberof LegOriginLocation
     */
    id: string;
    /**
     * (Full) Name of the location.
     * @type {string}
     * @memberof LegOriginLocation
     */
    name: string;
    /**
     * Type of the location.
     * @type {string}
     * @memberof LegOriginLocation
     */
    type: LegOriginLocationTypeEnum;
    /**
     * 
     * @type {LocationDetails}
     * @memberof LegOriginLocation
     */
    details: LocationDetails;
    /**
     * Planned departure time.
     * @type {Date}
     * @memberof LegOriginLocation
     */
    departureTimePlanned: Date;
    /**
     * Estimated departure time. If there is no estimated departure time, planned departure time gets duplicated.
     * @type {Date}
     * @memberof LegOriginLocation
     */
    departureTimeEstimated: Date;
}


/**
 * @export
 */
export const LegOriginLocationTypeEnum = {
    Address: 'address',
    Crossing: 'crossing',
    Gis: 'gis',
    Locality: 'locality',
    Parking: 'parking',
    Platform: 'platform',
    Poi: 'poi',
    PoiHierarchy: 'poiHierarchy',
    Sharing: 'sharing',
    Stop: 'stop',
    Street: 'street',
    Suburb: 'suburb',
    Unknown: 'unknown',
    Singlehouse: 'singlehouse'
} as const;
export type LegOriginLocationTypeEnum = typeof LegOriginLocationTypeEnum[keyof typeof LegOriginLocationTypeEnum];


/**
 * Check if a given object implements the LegOriginLocation interface.
 */
export function instanceOfLegOriginLocation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "details" in value;
    isInstance = isInstance && "departureTimePlanned" in value;
    isInstance = isInstance && "departureTimeEstimated" in value;

    return isInstance;
}

export function LegOriginLocationFromJSON(json: any): LegOriginLocation {
    return LegOriginLocationFromJSONTyped(json, false);
}

export function LegOriginLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegOriginLocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'type': json['type'],
        'details': LocationDetailsFromJSON(json['details']),
        'departureTimePlanned': (new Date(json['departureTimePlanned'])),
        'departureTimeEstimated': (new Date(json['departureTimeEstimated'])),
    };
}

export function LegOriginLocationToJSON(value?: LegOriginLocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'type': value.type,
        'details': LocationDetailsToJSON(value.details),
        'departureTimePlanned': (value.departureTimePlanned.toISOString()),
        'departureTimeEstimated': (value.departureTimeEstimated.toISOString()),
    };
}

