/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LegStatsCancellationStat } from './LegStatsCancellationStat';
import {
    LegStatsCancellationStatFromJSON,
    LegStatsCancellationStatFromJSONTyped,
    LegStatsCancellationStatToJSON,
} from './LegStatsCancellationStat';
import type { LegStatsDestinationDelayStats } from './LegStatsDestinationDelayStats';
import {
    LegStatsDestinationDelayStatsFromJSON,
    LegStatsDestinationDelayStatsFromJSONTyped,
    LegStatsDestinationDelayStatsToJSON,
} from './LegStatsDestinationDelayStats';
import type { LegStatsInterchangeReachableStat } from './LegStatsInterchangeReachableStat';
import {
    LegStatsInterchangeReachableStatFromJSON,
    LegStatsInterchangeReachableStatFromJSONTyped,
    LegStatsInterchangeReachableStatToJSON,
} from './LegStatsInterchangeReachableStat';
import type { LegStatsOriginDelayStats } from './LegStatsOriginDelayStats';
import {
    LegStatsOriginDelayStatsFromJSON,
    LegStatsOriginDelayStatsFromJSONTyped,
    LegStatsOriginDelayStatsToJSON,
} from './LegStatsOriginDelayStats';

/**
 * 
 * @export
 * @interface LegStats
 */
export interface LegStats {
    /**
     * 
     * @type {LegStatsOriginDelayStats}
     * @memberof LegStats
     */
    originDelayStats: LegStatsOriginDelayStats;
    /**
     * 
     * @type {LegStatsDestinationDelayStats}
     * @memberof LegStats
     */
    destinationDelayStats: LegStatsDestinationDelayStats;
    /**
     * 
     * @type {LegStatsInterchangeReachableStat}
     * @memberof LegStats
     */
    interchangeReachableStat: LegStatsInterchangeReachableStat;
    /**
     * 
     * @type {LegStatsCancellationStat}
     * @memberof LegStats
     */
    cancellationStat: LegStatsCancellationStat;
}

/**
 * Check if a given object implements the LegStats interface.
 */
export function instanceOfLegStats(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "originDelayStats" in value;
    isInstance = isInstance && "destinationDelayStats" in value;
    isInstance = isInstance && "interchangeReachableStat" in value;
    isInstance = isInstance && "cancellationStat" in value;

    return isInstance;
}

export function LegStatsFromJSON(json: any): LegStats {
    return LegStatsFromJSONTyped(json, false);
}

export function LegStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'originDelayStats': LegStatsOriginDelayStatsFromJSON(json['originDelayStats']),
        'destinationDelayStats': LegStatsDestinationDelayStatsFromJSON(json['destinationDelayStats']),
        'interchangeReachableStat': LegStatsInterchangeReachableStatFromJSON(json['interchangeReachableStat']),
        'cancellationStat': LegStatsCancellationStatFromJSON(json['cancellationStat']),
    };
}

export function LegStatsToJSON(value?: LegStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'originDelayStats': LegStatsOriginDelayStatsToJSON(value.originDelayStats),
        'destinationDelayStats': LegStatsDestinationDelayStatsToJSON(value.destinationDelayStats),
        'interchangeReachableStat': LegStatsInterchangeReachableStatToJSON(value.interchangeReachableStat),
        'cancellationStat': LegStatsCancellationStatToJSON(value.cancellationStat),
    };
}

