/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MaybeDelayStats } from './MaybeDelayStats';
import {
    MaybeDelayStatsFromJSON,
    MaybeDelayStatsFromJSONTyped,
    MaybeDelayStatsToJSON,
} from './MaybeDelayStats';

/**
 * 
 * @export
 * @interface LegStats
 */
export interface LegStats {
    /**
     * Delay statistics at origin.
     * @type {MaybeDelayStats}
     * @memberof LegStats
     */
    originDelayStats: MaybeDelayStats;
    /**
     * Delay statistics at destination.
     * @type {MaybeDelayStats}
     * @memberof LegStats
     */
    destinationDelayStats: MaybeDelayStats;
}

/**
 * Check if a given object implements the LegStats interface.
 */
export function instanceOfLegStats(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "originDelayStats" in value;
    isInstance = isInstance && "destinationDelayStats" in value;

    return isInstance;
}

export function LegStatsFromJSON(json: any): LegStats {
    return LegStatsFromJSONTyped(json, false);
}

export function LegStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'originDelayStats': MaybeDelayStatsFromJSON(json['originDelayStats']),
        'destinationDelayStats': MaybeDelayStatsFromJSON(json['destinationDelayStats']),
    };
}

export function LegStatsToJSON(value?: LegStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'originDelayStats': MaybeDelayStatsToJSON(value.originDelayStats),
        'destinationDelayStats': MaybeDelayStatsToJSON(value.destinationDelayStats),
    };
}

