/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    DelayStats,
    instanceOfDelayStats,
    DelayStatsFromJSON,
    DelayStatsFromJSONTyped,
    DelayStatsToJSON,
} from './DelayStats';
import {
    UnavailableStats,
    instanceOfUnavailableStats,
    UnavailableStatsFromJSON,
    UnavailableStatsFromJSONTyped,
    UnavailableStatsToJSON,
} from './UnavailableStats';

/**
 * @type LegStatsDestinationDelayStats
 * Delay statistics at destination of leg/trip.
 * @export
 */
export type LegStatsDestinationDelayStats = { status: 'available' } & DelayStats | { status: 'unavailable' } & UnavailableStats;

export function LegStatsDestinationDelayStatsFromJSON(json: any): LegStatsDestinationDelayStats {
    return LegStatsDestinationDelayStatsFromJSONTyped(json, false);
}

export function LegStatsDestinationDelayStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegStatsDestinationDelayStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['status']) {
        case 'available':
            return {...DelayStatsFromJSONTyped(json, true), status: 'available'};
        case 'unavailable':
            return {...UnavailableStatsFromJSONTyped(json, true), status: 'unavailable'};
        default:
            throw new Error(`No variant of LegStatsDestinationDelayStats exists with 'status=${json['status']}'`);
    }
}

export function LegStatsDestinationDelayStatsToJSON(value?: LegStatsDestinationDelayStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['status']) {
        case 'available':
            return DelayStatsToJSON(value);
        case 'unavailable':
            return UnavailableStatsToJSON(value);
        default:
            throw new Error(`No variant of LegStatsDestinationDelayStats exists with 'status=${value['status']}'`);
    }

}

