/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LegStats
 */
export interface LegStats {
    /**
     * Wether leg stats are available
     * @type {boolean}
     * @memberof LegStats
     */
    areAvailable: boolean;
    /**
     * The average delay.
     * @type {number}
     * @memberof LegStats
     */
    averageDelay: number;
    /**
     * The standard deviation of the delay.
     * @type {number}
     * @memberof LegStats
     */
    standardDeviation: number;
    /**
     * The maximum delay of the leg.
     * @type {number}
     * @memberof LegStats
     */
    maxDelay: number;
    /**
     * The minimum delay of the leg.
     * @type {number}
     * @memberof LegStats
     */
    minDelay: number;
}

/**
 * Check if a given object implements the LegStats interface.
 */
export function instanceOfLegStats(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "areAvailable" in value;
    isInstance = isInstance && "averageDelay" in value;
    isInstance = isInstance && "standardDeviation" in value;
    isInstance = isInstance && "maxDelay" in value;
    isInstance = isInstance && "minDelay" in value;

    return isInstance;
}

export function LegStatsFromJSON(json: any): LegStats {
    return LegStatsFromJSONTyped(json, false);
}

export function LegStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'areAvailable': json['areAvailable'],
        'averageDelay': json['averageDelay'],
        'standardDeviation': json['standardDeviation'],
        'maxDelay': json['maxDelay'],
        'minDelay': json['minDelay'],
    };
}

export function LegStatsToJSON(value?: LegStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'areAvailable': value.areAvailable,
        'averageDelay': value.averageDelay,
        'standardDeviation': value.standardDeviation,
        'maxDelay': value.maxDelay,
        'minDelay': value.minDelay,
    };
}

