/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocationNameDto
 */
export interface LocationNameDto {
    /**
     * Name of the location to search.
     * @type {string}
     * @memberof LocationNameDto
     */
    name: string;
    /**
     * Limit of the number of results.
     * @type {number}
     * @memberof LocationNameDto
     */
    limit?: number;
}

/**
 * Check if a given object implements the LocationNameDto interface.
 */
export function instanceOfLocationNameDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function LocationNameDtoFromJSON(json: any): LocationNameDto {
    return LocationNameDtoFromJSONTyped(json, false);
}

export function LocationNameDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationNameDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
    };
}

export function LocationNameDtoToJSON(value?: LocationNameDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'limit': value.limit,
    };
}

