/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationToJSON
} from './Location';

/**
 * 
 * @export
 * @interface LocationDetails
 */
export interface LocationDetails {
    /**
     * Short name of the location.
     * @type {string}
     * @memberof LocationDetails
     */
    shortName?: string;
    /**
     * Quality how well the given location meets the related query (biggest number is the best result).
     * @type {number}
     * @memberof LocationDetails
     */
    matchQuality?: number;
    /**
     * 
     * @type {Location}
     * @memberof LocationDetails
     */
    parent?: Location;
    /**
     * Latitude of the location.
     * @type {number}
     * @memberof LocationDetails
     */
    latitude?: number;
    /**
     * Longitude of the location.
     * @type {number}
     * @memberof LocationDetails
     */
    longitude?: number;
}

/**
 * Check if a given object implements the LocationDetails interface.
 */
export function instanceOfLocationDetails(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LocationDetailsFromJSON(json: any): LocationDetails {
    return LocationDetailsFromJSONTyped(json, false);
}

export function LocationDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'shortName': !exists(json, 'shortName') ? undefined : json['shortName'],
        'matchQuality': !exists(json, 'matchQuality') ? undefined : json['matchQuality'],
        'parent': !exists(json, 'parent') ? undefined : LocationFromJSON(json['parent']),
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
    };
}

export function LocationDetailsToJSON(value?: LocationDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'shortName': value.shortName,
        'matchQuality': value.matchQuality,
        'parent': LocationToJSON(value.parent),
        'latitude': value.latitude,
        'longitude': value.longitude,
    };
}
