/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LocationCoordinates } from './LocationCoordinates';
import {
    LocationCoordinatesFromJSON,
    LocationCoordinatesFromJSONTyped,
    LocationCoordinatesToJSON,
} from './LocationCoordinates';
import type { ParentLocation } from './ParentLocation';
import {
    ParentLocationFromJSON,
    ParentLocationFromJSONTyped,
    ParentLocationToJSON,
} from './ParentLocation';

/**
 * 
 * @export
 * @interface LocationDetails
 */
export interface LocationDetails {
    /**
     * Short name of the location. Can be empty string.
     * @type {string}
     * @memberof LocationDetails
     */
    shortName: string;
    /**
     * 
     * @type {LocationCoordinates}
     * @memberof LocationDetails
     */
    coordinates: LocationCoordinates;
    /**
     * 
     * @type {ParentLocation}
     * @memberof LocationDetails
     */
    parent: ParentLocation;
}

/**
 * Check if a given object implements the LocationDetails interface.
 */
export function instanceOfLocationDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "shortName" in value;
    isInstance = isInstance && "coordinates" in value;
    isInstance = isInstance && "parent" in value;

    return isInstance;
}

export function LocationDetailsFromJSON(json: any): LocationDetails {
    return LocationDetailsFromJSONTyped(json, false);
}

export function LocationDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shortName': json['shortName'],
        'coordinates': LocationCoordinatesFromJSON(json['coordinates']),
        'parent': ParentLocationFromJSON(json['parent']),
    };
}

export function LocationDetailsToJSON(value?: LocationDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shortName': value.shortName,
        'coordinates': LocationCoordinatesToJSON(value.coordinates),
        'parent': ParentLocationToJSON(value.parent),
    };
}

