/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LocationDetails } from './LocationDetails';
import {
    LocationDetailsFromJSON,
    LocationDetailsFromJSONTyped,
    LocationDetailsToJSON,
} from './LocationDetails';
import type { RatedLocation } from './RatedLocation';
import {
    RatedLocationFromJSON,
    RatedLocationFromJSONTyped,
    RatedLocationToJSON,
} from './RatedLocation';

/**
 * 
 * @export
 * @interface LocationWithAssignedStops
 */
export interface LocationWithAssignedStops {
    /**
     * Id of the location.
     * @type {string}
     * @memberof LocationWithAssignedStops
     */
    id: string;
    /**
     * (Full) Name of the location.
     * @type {string}
     * @memberof LocationWithAssignedStops
     */
    name: string;
    /**
     * Type of the location.
     * @type {string}
     * @memberof LocationWithAssignedStops
     */
    type: LocationWithAssignedStopsTypeEnum;
    /**
     * 
     * @type {LocationDetails}
     * @memberof LocationWithAssignedStops
     */
    details: LocationDetails;
    /**
     * All stops assigned to the location.
     * @type {Array<RatedLocation>}
     * @memberof LocationWithAssignedStops
     */
    assignedStops: Array<RatedLocation>;
}


/**
 * @export
 */
export const LocationWithAssignedStopsTypeEnum = {
    Address: 'address',
    Crossing: 'crossing',
    Gis: 'gis',
    Locality: 'locality',
    Parking: 'parking',
    Platform: 'platform',
    Poi: 'poi',
    PoiHierarchy: 'poiHierarchy',
    Sharing: 'sharing',
    Stop: 'stop',
    Street: 'street',
    Suburb: 'suburb',
    Unknown: 'unknown',
    Singlehouse: 'singlehouse'
} as const;
export type LocationWithAssignedStopsTypeEnum = typeof LocationWithAssignedStopsTypeEnum[keyof typeof LocationWithAssignedStopsTypeEnum];


/**
 * Check if a given object implements the LocationWithAssignedStops interface.
 */
export function instanceOfLocationWithAssignedStops(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "details" in value;
    isInstance = isInstance && "assignedStops" in value;

    return isInstance;
}

export function LocationWithAssignedStopsFromJSON(json: any): LocationWithAssignedStops {
    return LocationWithAssignedStopsFromJSONTyped(json, false);
}

export function LocationWithAssignedStopsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationWithAssignedStops {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'type': json['type'],
        'details': LocationDetailsFromJSON(json['details']),
        'assignedStops': ((json['assignedStops'] as Array<any>).map(RatedLocationFromJSON)),
    };
}

export function LocationWithAssignedStopsToJSON(value?: LocationWithAssignedStops | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'type': value.type,
        'details': LocationDetailsToJSON(value.details),
        'assignedStops': ((value.assignedStops as Array<any>).map(RatedLocationToJSON)),
    };
}

