/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MaybeLegStats
 */
export interface MaybeLegStats {
    /**
     * Wether leg stats are available
     * @type {boolean}
     * @memberof MaybeLegStats
     */
    areAvailable: boolean;
}

/**
 * Check if a given object implements the MaybeLegStats interface.
 */
export function instanceOfMaybeLegStats(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "areAvailable" in value;

    return isInstance;
}

export function MaybeLegStatsFromJSON(json: any): MaybeLegStats {
    return MaybeLegStatsFromJSONTyped(json, false);
}

export function MaybeLegStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaybeLegStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'areAvailable': json['areAvailable'],
    };
}

export function MaybeLegStatsToJSON(value?: MaybeLegStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'areAvailable': value.areAvailable,
    };
}

