/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ParentLocationDetails } from './ParentLocationDetails';
import {
    ParentLocationDetailsFromJSON,
    ParentLocationDetailsFromJSONTyped,
    ParentLocationDetailsToJSON,
} from './ParentLocationDetails';

/**
 * 
 * @export
 * @interface ParentLocation
 */
export interface ParentLocation {
    /**
     * Id of the location.
     * @type {string}
     * @memberof ParentLocation
     */
    id: string;
    /**
     * (Full) Name of the location.
     * @type {string}
     * @memberof ParentLocation
     */
    name: string;
    /**
     * Type of the location.
     * @type {string}
     * @memberof ParentLocation
     */
    type: ParentLocationTypeEnum;
    /**
     * 
     * @type {ParentLocationDetails}
     * @memberof ParentLocation
     */
    details: ParentLocationDetails;
}


/**
 * @export
 */
export const ParentLocationTypeEnum = {
    Address: 'address',
    Crossing: 'crossing',
    Gis: 'gis',
    Locality: 'locality',
    Parking: 'parking',
    Platform: 'platform',
    Poi: 'poi',
    PoiHierarchy: 'poiHierarchy',
    Sharing: 'sharing',
    Stop: 'stop',
    Street: 'street',
    Suburb: 'suburb',
    Unknown: 'unknown',
    Singlehouse: 'singlehouse'
} as const;
export type ParentLocationTypeEnum = typeof ParentLocationTypeEnum[keyof typeof ParentLocationTypeEnum];


/**
 * Check if a given object implements the ParentLocation interface.
 */
export function instanceOfParentLocation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "details" in value;

    return isInstance;
}

export function ParentLocationFromJSON(json: any): ParentLocation {
    return ParentLocationFromJSONTyped(json, false);
}

export function ParentLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParentLocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'type': json['type'],
        'details': ParentLocationDetailsFromJSON(json['details']),
    };
}

export function ParentLocationToJSON(value?: ParentLocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'type': value.type,
        'details': ParentLocationDetailsToJSON(value.details),
    };
}

