/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LocationDetails } from './LocationDetails';
import {
    LocationDetailsFromJSON,
    LocationDetailsFromJSONTyped,
    LocationDetailsToJSON,
} from './LocationDetails';

/**
 * 
 * @export
 * @interface RatedLocation
 */
export interface RatedLocation {
    /**
     * Id of the location.
     * @type {string}
     * @memberof RatedLocation
     */
    id: string;
    /**
     * (Full) Name of the location.
     * @type {string}
     * @memberof RatedLocation
     */
    name: string;
    /**
     * Type of the location.
     * @type {string}
     * @memberof RatedLocation
     */
    type: RatedLocationTypeEnum;
    /**
     * 
     * @type {LocationDetails}
     * @memberof RatedLocation
     */
    details: LocationDetails;
    /**
     * How well the location result meets the query (positive integers including zero, higher means better).
     * @type {number}
     * @memberof RatedLocation
     */
    rating: number;
}


/**
 * @export
 */
export const RatedLocationTypeEnum = {
    Address: 'address',
    Crossing: 'crossing',
    Gis: 'gis',
    Locality: 'locality',
    Parking: 'parking',
    Platform: 'platform',
    Poi: 'poi',
    PoiHierarchy: 'poiHierarchy',
    Sharing: 'sharing',
    Stop: 'stop',
    Street: 'street',
    Suburb: 'suburb',
    Unknown: 'unknown',
    Singlehouse: 'singlehouse'
} as const;
export type RatedLocationTypeEnum = typeof RatedLocationTypeEnum[keyof typeof RatedLocationTypeEnum];


/**
 * Check if a given object implements the RatedLocation interface.
 */
export function instanceOfRatedLocation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "details" in value;
    isInstance = isInstance && "rating" in value;

    return isInstance;
}

export function RatedLocationFromJSON(json: any): RatedLocation {
    return RatedLocationFromJSONTyped(json, false);
}

export function RatedLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatedLocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'type': json['type'],
        'details': LocationDetailsFromJSON(json['details']),
        'rating': json['rating'],
    };
}

export function RatedLocationToJSON(value?: RatedLocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'type': value.type,
        'details': LocationDetailsToJSON(value.details),
        'rating': value.rating,
    };
}

