/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Time
 */
export interface Time {
    /**
     * Time estimated.
     * @type {Date}
     * @memberof Time
     */
    estimated: Date;
    /**
     * Time planned.
     * @type {Date}
     * @memberof Time
     */
    planned: Date;
}

/**
 * Check if a given object implements the Time interface.
 */
export function instanceOfTime(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "estimated" in value;
    isInstance = isInstance && "planned" in value;

    return isInstance;
}

export function TimeFromJSON(json: any): Time {
    return TimeFromJSONTyped(json, false);
}

export function TimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Time {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'estimated': (new Date(json['estimated'])),
        'planned': (new Date(json['planned'])),
    };
}

export function TimeToJSON(value?: Time | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'estimated': (value.estimated.toISOString()),
        'planned': (value.planned.toISOString()),
    };
}

