/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Trip } from './Trip';
import {
    TripFromJSON,
    TripFromJSONTyped,
    TripToJSON,
} from './Trip';

/**
 * 
 * @export
 * @interface Transportation
 */
export interface Transportation {
    /**
     * Name of transportation vehicle.
     * @type {string}
     * @memberof Transportation
     */
    name?: string;
    /**
     * Trips depending on this transportation.
     * @type {Array<Trip>}
     * @memberof Transportation
     */
    trips?: Array<Trip>;
}

/**
 * Check if a given object implements the Transportation interface.
 */
export function instanceOfTransportation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TransportationFromJSON(json: any): Transportation {
    return TransportationFromJSONTyped(json, false);
}

export function TransportationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transportation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'trips': !exists(json, 'trips') ? undefined : ((json['trips'] as Array<any>).map(TripFromJSON)),
    };
}

export function TransportationToJSON(value?: Transportation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'trips': value.trips === undefined ? undefined : ((value.trips as Array<any>).map(TripToJSON)),
    };
}

