/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnavailableLegStats
 */
export interface UnavailableLegStats {
    /**
     * Wether leg stats are available
     * @type {boolean}
     * @memberof UnavailableLegStats
     */
    areAvailable: boolean;
    /**
     * The reason, why the data is not available
     * @type {string}
     * @memberof UnavailableLegStats
     */
    reason: string;
}

/**
 * Check if a given object implements the UnavailableLegStats interface.
 */
export function instanceOfUnavailableLegStats(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "areAvailable" in value;
    isInstance = isInstance && "reason" in value;

    return isInstance;
}

export function UnavailableLegStatsFromJSON(json: any): UnavailableLegStats {
    return UnavailableLegStatsFromJSONTyped(json, false);
}

export function UnavailableLegStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnavailableLegStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'areAvailable': json['areAvailable'],
        'reason': json['reason'],
    };
}

export function UnavailableLegStatsToJSON(value?: UnavailableLegStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'areAvailable': value.areAvailable,
        'reason': value.reason,
    };
}

