/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Swagger
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnavailableStats
 */
export interface UnavailableStats {
    /**
     * Status of the leg stats.
     * @type {string}
     * @memberof UnavailableStats
     */
    status: UnavailableStatsStatusEnum;
    /**
     * The reason, why the data is not available
     * @type {string}
     * @memberof UnavailableStats
     */
    reason: string;
}


/**
 * @export
 */
export const UnavailableStatsStatusEnum = {
    Available: 'available',
    Unavailable: 'unavailable'
} as const;
export type UnavailableStatsStatusEnum = typeof UnavailableStatsStatusEnum[keyof typeof UnavailableStatsStatusEnum];


/**
 * Check if a given object implements the UnavailableStats interface.
 */
export function instanceOfUnavailableStats(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "reason" in value;

    return isInstance;
}

export function UnavailableStatsFromJSON(json: any): UnavailableStats {
    return UnavailableStatsFromJSONTyped(json, false);
}

export function UnavailableStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnavailableStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'reason': json['reason'],
    };
}

export function UnavailableStatsToJSON(value?: UnavailableStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'reason': value.reason,
    };
}

